# Preprocessor settings
SET(${MODULE_NAME_UPPER}_DEPENDENCIES "tsd.common;tsd.communication.event")
SET(${MODULE_NAME_UPPER}_INCLUDES "${MODULE_PATH}/src")
SET(${MODULE_NAME_UPPER}_DEFINITIONS "")

# Linker settings
SET (${MODULE_NAME_UPPER}_LINK_LIBRARIES ${MODULE_NAME})

# API Settings
SET (${MODULE_NAME_UPPER}_DEFINITIONS -D${MODULE_NAME_UPPER_NODOTS}_API_VERSION=200)
